version: '3'

services:
  web_app:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
      --access-logfile -
      --reload
      "web_app.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/web_app'
    ports:
      - '8000:8000'

  postgres:
    image: 'postgres:10.10'
    environment:
      POSTGRES_USER: 'devuser'
      POSTGRES_PASSWORD: 'devpassword'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5433:5432'

volumes:
  postgres: